import Head from 'next/head';
import Image from 'next/image';
import { authUser } from '../services/auth';
import { useRouter } from 'next/router';
import styles from '../styles/Home.module.css';
import toast, { Toaster } from 'react-hot-toast';
import { getCookies, setCookie, deleteCookie } from 'cookies-next';
import useFirestore from '../hooks/useFirestore';

export default function Home() {
  const { checkIfUserExist, createUser } = useFirestore();
  const router = useRouter();

  const handleAuth = async () => {
    const response = await authUser();
    // @ts-ignore
    if (response.error) {
      // @ts-ignore
      toast.error(response.error);
    } else {
      toast.success('Login Successfully');
      // @ts-ignore
      setCookie('email', response.user!.email, { path: '/' });
      // @ts-ignore
      checkIfUserExist(response.user.email!).then((exist) => {
        if (!exist) {
          // @ts-ignore
          createUser(response.user.email!);
        }
      });

      setTimeout(() => {
        router.push('/home');
      }, 1000);
    }
  };

  return (
    <div className={styles.container}>
      <Head>
        <title>Gipghy</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        {/* <button onClick={handleAuth}>Login with Google</button> */}
        <Image
          src="https://media.giphy.com/avatars/default2/200w.gif"
          alt="Giphy"
          width={250}
          height={250}
          className={styles.image_login}
        />
        <div id="gSignInWrapper" onClick={handleAuth}>
          <div
            id="customBtn"
            className={`${styles.customGPlusSignIn} ${styles.customBtn}`}
          >
            <span className={styles.icon}></span>
            <span className={styles.buttonText}>Login with Google</span>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <Toaster />
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
